salesforce/sa11y

CHANGELOG.md, package.json, packages/test-integration/package.json, packages/wdio/__tests__/wdio.test.ts, packages/wdio/package.json, packages/wdio/src/wdio.ts
* Replace custom polling logic to use [WebdriverIO's wait util](https://webdriver.io/docs/api/browser/waitUntil/) instead as it reliably fixes the race condition 
* Increase timeout to 10s based on e2e testing with complex/large pages
=> fix(wdio): axe undefined error due to race condition

package.json, yarn.lock
Updating chromedriver to something modern.
=> chore(deps): update chromedriver to 103.0.0

packages/test-utils/__data__/noA11yIssues.html
The contents of this `<script>` are never actually executed in Jest, so this adds a comment to explain that.
=> test: add comment about unexecuted script

.circleci/config.yml
Update the node and browser-tools orbs to the latest.
=> build(circleci): update orbs

.github/workflows/codeql-analysis.yml, .github/workflows/pr-title-check.yml
Updating all github actions to the latest
=> chore(workflows): update GitHub actions

package.json, yarn.lock
Updating chromedrive to the latest
=> chore(deps): update chromedriver

package.json, yarn.lock
Update prettier to the latest.
=> chore(deps): update prettier

package.json, yarn.lock
=> chore(deps): lerna major upgrade

package.json, yarn.lock
=> chore(deps): update depcheck

package.json, yarn.lock
It's a major release since they dropped node12
=> chore(deps): update lint-staged

.circleci/config.yml, package.json, yarn.lock
Remove the deprecated [codecov](https://www.npmjs.com/package/codecov) NPM package, replace with CircleCI orb from https://circleci.com/developer/orbs/orb/codecov/codecov
=> build(circleci): use codecov orb

package.json, packages/browser-lib/tsconfig.json, tsconfig.common.json, tsconfig.json, yarn.lock
Using recommended TSConfig template for node14
=> feat: tsconfig package for tsconfig.json

renovate.json
- automerge linters, tests, and types.
- add [security] label for vulnerabilities.
- maintain lock files once a week
=> build(renovate): update renovate configuration

.gitignore
Do not accidentally commit Jest results (junit.xml)
=> chore: gitignore test results

jest.config.js
Jest was running integration tests twice.
=> build(jest): don't run tests twice

.github/workflows/scorecards.yml, README.md
Adding the OSSF Scorecard github action, and linking the badge.
Mostly followed the guide from https://github.com/ossf/scorecard-action#installation
=> feat: add OSSF Scorecard action and badge

README.md
The workflow name was renamed. This fixes the badge.
=> docs(README): fix build status badge

lerna.json, packages/assert/package.json, packages/browser-lib/package.json, packages/common/package.json, packages/format/package.json, packages/jest/package.json, packages/preset-rules/package.json, packages/test-integration/package.json, packages/test-utils/package.json, packages/wdio/package.json
=> chore: update sa11y packages with latest version v5.1.0

package.json, yarn.lock
=> chore(chromedriver): upgrade chromedriver to 115v

packages/jest/README.md, packages/jest/__tests__/setup.test.ts, packages/jest/package.json, packages/jest/src/automatic.ts, packages/jest/src/setup.ts, yarn.lock
Improve automatic a11y coverage for jest tests
=> feat!: improve automatic checks coverage

packages/format/src/format.ts, packages/format/src/index.ts, packages/jest/__tests__/__snapshots__/groupViolationResultsProcessor.test.ts.snap, packages/jest/__tests__/automatic.test.ts, packages/jest/__tests__/groupViolationResultsProcessor.test.ts, packages/jest/src/automatic.ts, packages/jest/src/groupViolationResultsProcessor.ts, packages/test-utils/__data__/sa11y-custom-rules-invalid.json, packages/test-utils/src/index.ts, packages/test-utils/src/test-data.ts
=> Revert "feat: added the ability to report AxeError"
